"""
Allowlist sanitizer for the HTML fragments a saved report renders with ``|safe``.

``interpretation`` and the CRR ``lattice`` are generated by the server, but the
screen saves them from the page (``innerHTML``), so the stored value is whatever
the browser sent. This keeps the tags those fragments use and drops everything
else: scripts, event handlers, links, images, styles.
"""
import re
from html import escape
from html.parser import HTMLParser

ALLOWED_TAGS = {
    'h4', 'h5', 'h6', 'p', 'br', 'hr', 'strong', 'b', 'em', 'i', 'u', 'code', 'small', 'sub', 'sup',
    'ul', 'ol', 'li', 'div', 'span', 'table', 'thead', 'tbody', 'tfoot', 'tr', 'th', 'td',
}
VOID_TAGS = {'br', 'hr'}
# Tags whose text must go too, not just the tag.
DROP_WITH_CONTENT = {'script', 'style', 'template', 'noscript', 'iframe', 'object', 'svg', 'math', 'textarea', 'title'}

_CLASS_RE = re.compile(r'^[\w\s-]*$')
_SPAN_RE = re.compile(r'^\d{1,3}$')


def _clean_attribute(name, value):
    value = value or ''
    if name == 'class' and _CLASS_RE.match(value):
        return value
    if name in ('colspan', 'rowspan') and _SPAN_RE.match(value):
        return value
    return None


class _Sanitizer(HTMLParser):
    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.parts = []
        self.open_tags = []
        self.skip_depth = 0

    def handle_starttag(self, tag, attrs):
        if tag in DROP_WITH_CONTENT:
            self.skip_depth += 1
            return
        if self.skip_depth or tag not in ALLOWED_TAGS:
            return
        kept = ''
        for name, value in attrs:
            clean = _clean_attribute(name, value)
            if clean is not None:
                kept += f' {name}="{escape(clean, quote=True)}"'
        self.parts.append(f'<{tag}{kept}>')
        if tag not in VOID_TAGS:
            self.open_tags.append(tag)

    def handle_startendtag(self, tag, attrs):
        self.handle_starttag(tag, attrs)
        if tag not in VOID_TAGS:
            self.handle_endtag(tag)

    def handle_endtag(self, tag):
        if tag in DROP_WITH_CONTENT:
            self.skip_depth = max(0, self.skip_depth - 1)
            return
        if self.skip_depth or tag not in self.open_tags:
            return
        # Close anything left open inside this tag, so the output stays balanced.
        while self.open_tags:
            open_tag = self.open_tags.pop()
            self.parts.append(f'</{open_tag}>')
            if open_tag == tag:
                break

    def handle_data(self, data):
        if not self.skip_depth:
            self.parts.append(escape(data, quote=False))

    def result(self):
        self.close()
        return ''.join(self.parts) + ''.join(f'</{tag}>' for tag in reversed(self.open_tags))


def sanitize_report_html(html):
    if not html:
        return ''
    sanitizer = _Sanitizer()
    sanitizer.feed(str(html))
    return sanitizer.result()
