# Generated by Django 4.2 on 2025-11-14 11:29

import django.core.validators
from django.db import migrations, models
import financial_options.models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_options', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finantialmodels',
            name='name',
            field=models.CharField(default='Financial Model', max_length=255),
        ),
        migrations.AlterField(
            model_name='finantialmodels',
            name='model_type',
            field=models.CharField(blank=True, choices=[('BLACK_SCHOLES', 'Black-Scholes'), ('BLACK_SCHOLES_MERTON', 'Black-Scholes-Merton'), ('GENERALIZED_BLACK_SCHOLES_MERTON', 'Generalized Black-Scholes-Merton'), ('COX_ROSS', 'Cox-Ross Binomial'), ('MONTE_CARLO_EUROPEAN', 'Monte-carlo European'), ('MONTE_CARLO_AMERICAN', 'Monte-carlo American')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='finantialmodels',
            name='report',
            field=models.FileField(blank=True, null=True, upload_to=financial_options.models._get_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='PDF Report'),
        ),
    ]
