# Generated by Django 4.2 on 2026-09-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_options', '0003_alter_finantialmodels_model_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finantialmodels',
            name='model_type',
            field=models.CharField(blank=True, choices=[('BLACK_SCHOLES', 'Black-Scholes'), ('BLACK_SCHOLES_MERTON', 'Black-Scholes-Merton'), ('GENERALIZED_BLACK_SCHOLES_MERTON', 'Generalized Black-Scholes-Merton'), ('COX_ROSS', 'Cox-Ross Binomial'), ('MONTE_CARLO_EUROPEAN', 'Monte-carlo European'), ('MONTE_CARLO_AMERICAN', 'Monte-carlo American'), ('FDM_EUROPEAN', 'Finite Difference European'), ('CALL_PUT_PAYOFF', 'Call & Put Payoff'), ('ASSET_PUT_COMBINATION', 'Asset + Put Combination'), ('BULL_BEAR_SPREAD', 'Bull / Bear Spread'), ('COLLAR', 'Collar'), ('RETURN_VOLATILITY', 'Return & Volatility')], max_length=100, null=True),
        ),
    ]
